//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 10:05:02 PM CEST 
//


package com.github.clentfort.dota2.dota;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ability complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ability">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://clentfort.github.com/dota2/dota}abilityType"/>
 *         &lt;element name="behavior" type="{http://clentfort.github.com/dota2/dota}abilityBehavior"/>
 *         &lt;element name="castRange" type="{http://clentfort.github.com/dota2/dota}abilityLevelBasedType" maxOccurs="4"/>
 *         &lt;element name="channelTime" type="{http://clentfort.github.com/dota2/dota}abilityLevelBasedType" maxOccurs="4"/>
 *         &lt;element name="cooldown" type="{http://clentfort.github.com/dota2/dota}abilityLevelBasedType" maxOccurs="4"/>
 *         &lt;element name="duration" type="{http://clentfort.github.com/dota2/dota}abilityLevelBasedType" maxOccurs="4"/>
 *         &lt;element name="damage" type="{http://clentfort.github.com/dota2/dota}abilityLevelBasedType" maxOccurs="4"/>
 *         &lt;element name="manacost" type="{http://clentfort.github.com/dota2/dota}abilityLevelBasedType" maxOccurs="4"/>
 *         &lt;element name="special" type="{http://clentfort.github.com/dota2/dota}abilitySpecial" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ability", propOrder = {
    "name",
    "type",
    "behavior",
    "castRange",
    "channelTime",
    "cooldown",
    "duration",
    "damage",
    "manacost",
    "special"
})
@XmlSeeAlso({
    Item.class
})
public class Ability {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected String behavior;
    @XmlElement(required = true)
    protected List<AbilityLevelBasedType> castRange;
    @XmlElement(required = true)
    protected List<AbilityLevelBasedType> channelTime;
    @XmlElement(required = true)
    protected List<AbilityLevelBasedType> cooldown;
    @XmlElement(required = true)
    protected List<AbilityLevelBasedType> duration;
    @XmlElement(required = true)
    protected List<AbilityLevelBasedType> damage;
    @XmlElement(required = true)
    protected List<AbilityLevelBasedType> manacost;
    @XmlElement(required = true)
    protected List<AbilitySpecial> special;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the behavior property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBehavior() {
        return behavior;
    }

    /**
     * Sets the value of the behavior property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBehavior(String value) {
        this.behavior = value;
    }

    /**
     * Gets the value of the castRange property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the castRange property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCastRange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbilityLevelBasedType }
     * 
     * 
     */
    public List<AbilityLevelBasedType> getCastRange() {
        if (castRange == null) {
            castRange = new ArrayList<AbilityLevelBasedType>();
        }
        return this.castRange;
    }

    /**
     * Gets the value of the channelTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channelTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChannelTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbilityLevelBasedType }
     * 
     * 
     */
    public List<AbilityLevelBasedType> getChannelTime() {
        if (channelTime == null) {
            channelTime = new ArrayList<AbilityLevelBasedType>();
        }
        return this.channelTime;
    }

    /**
     * Gets the value of the cooldown property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cooldown property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCooldown().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbilityLevelBasedType }
     * 
     * 
     */
    public List<AbilityLevelBasedType> getCooldown() {
        if (cooldown == null) {
            cooldown = new ArrayList<AbilityLevelBasedType>();
        }
        return this.cooldown;
    }

    /**
     * Gets the value of the duration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the duration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDuration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbilityLevelBasedType }
     * 
     * 
     */
    public List<AbilityLevelBasedType> getDuration() {
        if (duration == null) {
            duration = new ArrayList<AbilityLevelBasedType>();
        }
        return this.duration;
    }

    /**
     * Gets the value of the damage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the damage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDamage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbilityLevelBasedType }
     * 
     * 
     */
    public List<AbilityLevelBasedType> getDamage() {
        if (damage == null) {
            damage = new ArrayList<AbilityLevelBasedType>();
        }
        return this.damage;
    }

    /**
     * Gets the value of the manacost property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the manacost property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManacost().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbilityLevelBasedType }
     * 
     * 
     */
    public List<AbilityLevelBasedType> getManacost() {
        if (manacost == null) {
            manacost = new ArrayList<AbilityLevelBasedType>();
        }
        return this.manacost;
    }

    /**
     * Gets the value of the special property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the special property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecial().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbilitySpecial }
     * 
     * 
     */
    public List<AbilitySpecial> getSpecial() {
        if (special == null) {
            special = new ArrayList<AbilitySpecial>();
        }
        return this.special;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
