//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 10:05:02 PM CEST 
//


package com.github.clentfort.dota2.dota;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for heroRole.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="heroRole">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="carry"/>
 *     &lt;enumeration value="initiator"/>
 *     &lt;enumeration value="ganker"/>
 *     &lt;enumeration value="support"/>
 *     &lt;enumeration value="pusher"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "heroRole")
@XmlEnum
public enum HeroRole {

    @XmlEnumValue("carry")
    CARRY("carry"),
    @XmlEnumValue("initiator")
    INITIATOR("initiator"),
    @XmlEnumValue("ganker")
    GANKER("ganker"),
    @XmlEnumValue("support")
    SUPPORT("support"),
    @XmlEnumValue("pusher")
    PUSHER("pusher");
    private final String value;

    HeroRole(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HeroRole fromValue(String v) {
        for (HeroRole c: HeroRole.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
