//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 10:05:02 PM CEST 
//


package com.github.clentfort.dota2.dota;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="item">
 *   &lt;complexContent>
 *     &lt;extension base="{http://clentfort.github.com/dota2/dota}ability">
 *       &lt;sequence>
 *         &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="initialCharges" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="combineable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="permanent" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="stackable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="recipe" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="droppable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="purchasable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="sellable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="requiresCharges" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="killable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="disassemblable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="shareability" type="{http://clentfort.github.com/dota2/dota}itemShareability"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "item", propOrder = {
    "cost",
    "initialCharges",
    "combineable",
    "permanent",
    "stackable",
    "recipe",
    "droppable",
    "purchasable",
    "sellable",
    "requiresCharges",
    "killable",
    "disassemblable",
    "shareability"
})
public class Item
    extends Ability
{

    protected int cost;
    protected int initialCharges;
    protected boolean combineable;
    protected boolean permanent;
    protected boolean stackable;
    protected boolean recipe;
    protected boolean droppable;
    protected boolean purchasable;
    protected boolean sellable;
    protected boolean requiresCharges;
    protected boolean killable;
    protected boolean disassemblable;
    @XmlElement(required = true)
    protected String shareability;

    /**
     * Gets the value of the cost property.
     * 
     */
    public int getCost() {
        return cost;
    }

    /**
     * Sets the value of the cost property.
     * 
     */
    public void setCost(int value) {
        this.cost = value;
    }

    /**
     * Gets the value of the initialCharges property.
     * 
     */
    public int getInitialCharges() {
        return initialCharges;
    }

    /**
     * Sets the value of the initialCharges property.
     * 
     */
    public void setInitialCharges(int value) {
        this.initialCharges = value;
    }

    /**
     * Gets the value of the combineable property.
     * 
     */
    public boolean isCombineable() {
        return combineable;
    }

    /**
     * Sets the value of the combineable property.
     * 
     */
    public void setCombineable(boolean value) {
        this.combineable = value;
    }

    /**
     * Gets the value of the permanent property.
     * 
     */
    public boolean isPermanent() {
        return permanent;
    }

    /**
     * Sets the value of the permanent property.
     * 
     */
    public void setPermanent(boolean value) {
        this.permanent = value;
    }

    /**
     * Gets the value of the stackable property.
     * 
     */
    public boolean isStackable() {
        return stackable;
    }

    /**
     * Sets the value of the stackable property.
     * 
     */
    public void setStackable(boolean value) {
        this.stackable = value;
    }

    /**
     * Gets the value of the recipe property.
     * 
     */
    public boolean isRecipe() {
        return recipe;
    }

    /**
     * Sets the value of the recipe property.
     * 
     */
    public void setRecipe(boolean value) {
        this.recipe = value;
    }

    /**
     * Gets the value of the droppable property.
     * 
     */
    public boolean isDroppable() {
        return droppable;
    }

    /**
     * Sets the value of the droppable property.
     * 
     */
    public void setDroppable(boolean value) {
        this.droppable = value;
    }

    /**
     * Gets the value of the purchasable property.
     * 
     */
    public boolean isPurchasable() {
        return purchasable;
    }

    /**
     * Sets the value of the purchasable property.
     * 
     */
    public void setPurchasable(boolean value) {
        this.purchasable = value;
    }

    /**
     * Gets the value of the sellable property.
     * 
     */
    public boolean isSellable() {
        return sellable;
    }

    /**
     * Sets the value of the sellable property.
     * 
     */
    public void setSellable(boolean value) {
        this.sellable = value;
    }

    /**
     * Gets the value of the requiresCharges property.
     * 
     */
    public boolean isRequiresCharges() {
        return requiresCharges;
    }

    /**
     * Sets the value of the requiresCharges property.
     * 
     */
    public void setRequiresCharges(boolean value) {
        this.requiresCharges = value;
    }

    /**
     * Gets the value of the killable property.
     * 
     */
    public boolean isKillable() {
        return killable;
    }

    /**
     * Sets the value of the killable property.
     * 
     */
    public void setKillable(boolean value) {
        this.killable = value;
    }

    /**
     * Gets the value of the disassemblable property.
     * 
     */
    public boolean isDisassemblable() {
        return disassemblable;
    }

    /**
     * Sets the value of the disassemblable property.
     * 
     */
    public void setDisassemblable(boolean value) {
        this.disassemblable = value;
    }

    /**
     * Gets the value of the shareability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShareability() {
        return shareability;
    }

    /**
     * Sets the value of the shareability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShareability(String value) {
        this.shareability = value;
    }

}
