//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 10:05:02 PM CEST 
//


package com.github.clentfort.dota2.dota;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.clentfort.dota2.dota package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.clentfort.dota2.dota
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Unit }
     * 
     */
    public Unit createUnit() {
        return new Unit();
    }

    /**
     * Create an instance of {@link Unit.Bounty }
     * 
     */
    public Unit.Bounty createUnitBounty() {
        return new Unit.Bounty();
    }

    /**
     * Create an instance of {@link Unit.Attack }
     * 
     */
    public Unit.Attack createUnitAttack() {
        return new Unit.Attack();
    }

    /**
     * Create an instance of {@link Heroes }
     * 
     */
    public Heroes createHeroes() {
        return new Heroes();
    }

    /**
     * Create an instance of {@link Hero }
     * 
     */
    public Hero createHero() {
        return new Hero();
    }

    /**
     * Create an instance of {@link com.github.clentfort.dota2.dota.Abilities }
     * 
     */
    public com.github.clentfort.dota2.dota.Abilities createAbilities() {
        return new com.github.clentfort.dota2.dota.Abilities();
    }

    /**
     * Create an instance of {@link Ability }
     * 
     */
    public Ability createAbility() {
        return new Ability();
    }

    /**
     * Create an instance of {@link Items }
     * 
     */
    public Items createItems() {
        return new Items();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link Units }
     * 
     */
    public Units createUnits() {
        return new Units();
    }

    /**
     * Create an instance of {@link UnitStatus }
     * 
     */
    public UnitStatus createUnitStatus() {
        return new UnitStatus();
    }

    /**
     * Create an instance of {@link UnitAttribute }
     * 
     */
    public UnitAttribute createUnitAttribute() {
        return new UnitAttribute();
    }

    /**
     * Create an instance of {@link AbilitySpecial }
     * 
     */
    public AbilitySpecial createAbilitySpecial() {
        return new AbilitySpecial();
    }

    /**
     * Create an instance of {@link AbilityLevelBasedType }
     * 
     */
    public AbilityLevelBasedType createAbilityLevelBasedType() {
        return new AbilityLevelBasedType();
    }

    /**
     * Create an instance of {@link Unit.Abilities }
     * 
     */
    public Unit.Abilities createUnitAbilities() {
        return new Unit.Abilities();
    }

    /**
     * Create an instance of {@link Unit.Armor }
     * 
     */
    public Unit.Armor createUnitArmor() {
        return new Unit.Armor();
    }

    /**
     * Create an instance of {@link Unit.Attributes }
     * 
     */
    public Unit.Attributes createUnitAttributes() {
        return new Unit.Attributes();
    }

    /**
     * Create an instance of {@link Unit.Movement }
     * 
     */
    public Unit.Movement createUnitMovement() {
        return new Unit.Movement();
    }

    /**
     * Create an instance of {@link Unit.Stats }
     * 
     */
    public Unit.Stats createUnitStats() {
        return new Unit.Stats();
    }

    /**
     * Create an instance of {@link Unit.Vision }
     * 
     */
    public Unit.Vision createUnitVision() {
        return new Unit.Vision();
    }

    /**
     * Create an instance of {@link Unit.Bounty.Gold }
     * 
     */
    public Unit.Bounty.Gold createUnitBountyGold() {
        return new Unit.Bounty.Gold();
    }

    /**
     * Create an instance of {@link Unit.Attack.Damage }
     * 
     */
    public Unit.Attack.Damage createUnitAttackDamage() {
        return new Unit.Attack.Damage();
    }

}
