//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 10:05:02 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://clentfort.github.com/dota2/dota", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.github.clentfort.dota2.dota;
