//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 10:05:02 PM CEST 
//


package com.github.clentfort.dota2.dota;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for unit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="unit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="abilities">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ability" type="{http://clentfort.github.com/dota2/dota}ability" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="armor">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="physical" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="magical" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attack">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="damage">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="max" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="min" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                           &lt;attribute ref="{http://clentfort.github.com/dota2/dota}damageType"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="rate" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="range" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="projectileSpeed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute ref="{http://clentfort.github.com/dota2/dota}attackCapabilitie"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attributes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="strength" type="{http://clentfort.github.com/dota2/dota}unitAttribute"/>
 *                   &lt;element name="intelligence" type="{http://clentfort.github.com/dota2/dota}unitAttribute"/>
 *                   &lt;element name="agility" type="{http://clentfort.github.com/dota2/dota}unitAttribute"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="primary" default="strength">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="strength"/>
 *                       &lt;enumeration value="intelligence"/>
 *                       &lt;enumeration value="agility"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="bounty">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="xp" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="gold">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="max" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="min" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="movement">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="turnRate" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="stats">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="health" type="{http://clentfort.github.com/dota2/dota}unitStatus"/>
 *                   &lt;element name="mana" type="{http://clentfort.github.com/dota2/dota}unitStatus"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="vision">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="day" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="night" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="neutral" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="ancient" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "unit", propOrder = {
    "name",
    "abilities",
    "armor",
    "attack",
    "attributes",
    "bounty",
    "movement",
    "stats",
    "vision"
})
@XmlSeeAlso({
    Hero.class
})
public class Unit {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected Unit.Abilities abilities;
    @XmlElement(required = true)
    protected Unit.Armor armor;
    @XmlElement(required = true)
    protected Unit.Attack attack;
    @XmlElement(required = true)
    protected Unit.Attributes attributes;
    @XmlElement(required = true)
    protected Unit.Bounty bounty;
    @XmlElement(required = true)
    protected Unit.Movement movement;
    @XmlElement(required = true)
    protected Unit.Stats stats;
    @XmlElement(required = true)
    protected Unit.Vision vision;
    @XmlAttribute(name = "neutral")
    protected Boolean neutral;
    @XmlAttribute(name = "ancient")
    protected Boolean ancient;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the abilities property.
     * 
     * @return
     *     possible object is
     *     {@link Unit.Abilities }
     *     
     */
    public Unit.Abilities getAbilities() {
        return abilities;
    }

    /**
     * Sets the value of the abilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unit.Abilities }
     *     
     */
    public void setAbilities(Unit.Abilities value) {
        this.abilities = value;
    }

    /**
     * Gets the value of the armor property.
     * 
     * @return
     *     possible object is
     *     {@link Unit.Armor }
     *     
     */
    public Unit.Armor getArmor() {
        return armor;
    }

    /**
     * Sets the value of the armor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unit.Armor }
     *     
     */
    public void setArmor(Unit.Armor value) {
        this.armor = value;
    }

    /**
     * Gets the value of the attack property.
     * 
     * @return
     *     possible object is
     *     {@link Unit.Attack }
     *     
     */
    public Unit.Attack getAttack() {
        return attack;
    }

    /**
     * Sets the value of the attack property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unit.Attack }
     *     
     */
    public void setAttack(Unit.Attack value) {
        this.attack = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link Unit.Attributes }
     *     
     */
    public Unit.Attributes getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unit.Attributes }
     *     
     */
    public void setAttributes(Unit.Attributes value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the bounty property.
     * 
     * @return
     *     possible object is
     *     {@link Unit.Bounty }
     *     
     */
    public Unit.Bounty getBounty() {
        return bounty;
    }

    /**
     * Sets the value of the bounty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unit.Bounty }
     *     
     */
    public void setBounty(Unit.Bounty value) {
        this.bounty = value;
    }

    /**
     * Gets the value of the movement property.
     * 
     * @return
     *     possible object is
     *     {@link Unit.Movement }
     *     
     */
    public Unit.Movement getMovement() {
        return movement;
    }

    /**
     * Sets the value of the movement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unit.Movement }
     *     
     */
    public void setMovement(Unit.Movement value) {
        this.movement = value;
    }

    /**
     * Gets the value of the stats property.
     * 
     * @return
     *     possible object is
     *     {@link Unit.Stats }
     *     
     */
    public Unit.Stats getStats() {
        return stats;
    }

    /**
     * Sets the value of the stats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unit.Stats }
     *     
     */
    public void setStats(Unit.Stats value) {
        this.stats = value;
    }

    /**
     * Gets the value of the vision property.
     * 
     * @return
     *     possible object is
     *     {@link Unit.Vision }
     *     
     */
    public Unit.Vision getVision() {
        return vision;
    }

    /**
     * Sets the value of the vision property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unit.Vision }
     *     
     */
    public void setVision(Unit.Vision value) {
        this.vision = value;
    }

    /**
     * Gets the value of the neutral property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNeutral() {
        if (neutral == null) {
            return false;
        } else {
            return neutral;
        }
    }

    /**
     * Sets the value of the neutral property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNeutral(Boolean value) {
        this.neutral = value;
    }

    /**
     * Gets the value of the ancient property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAncient() {
        if (ancient == null) {
            return false;
        } else {
            return ancient;
        }
    }

    /**
     * Sets the value of the ancient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAncient(Boolean value) {
        this.ancient = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ability" type="{http://clentfort.github.com/dota2/dota}ability" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ability"
    })
    public static class Abilities {

        protected List<Ability> ability;

        /**
         * Gets the value of the ability property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ability property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAbility().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Ability }
         * 
         * 
         */
        public List<Ability> getAbility() {
            if (ability == null) {
                ability = new ArrayList<Ability>();
            }
            return this.ability;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="physical" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="magical" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "physical",
        "magical"
    })
    public static class Armor {

        protected int physical;
        protected int magical;

        /**
         * Gets the value of the physical property.
         * 
         */
        public int getPhysical() {
            return physical;
        }

        /**
         * Sets the value of the physical property.
         * 
         */
        public void setPhysical(int value) {
            this.physical = value;
        }

        /**
         * Gets the value of the magical property.
         * 
         */
        public int getMagical() {
            return magical;
        }

        /**
         * Sets the value of the magical property.
         * 
         */
        public void setMagical(int value) {
            this.magical = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="damage">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="max" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="min" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *                 &lt;attribute ref="{http://clentfort.github.com/dota2/dota}damageType"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="rate" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="range" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="projectileSpeed" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute ref="{http://clentfort.github.com/dota2/dota}attackCapabilitie"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "damage",
        "rate",
        "range",
        "projectileSpeed"
    })
    public static class Attack {

        @XmlElement(required = true)
        protected Unit.Attack.Damage damage;
        protected float rate;
        protected float range;
        @XmlElement(required = true)
        protected String projectileSpeed;
        @XmlAttribute(name = "attackCapabilitie", namespace = "http://clentfort.github.com/dota2/dota")
        protected String attackCapabilitie;

        /**
         * Gets the value of the damage property.
         * 
         * @return
         *     possible object is
         *     {@link Unit.Attack.Damage }
         *     
         */
        public Unit.Attack.Damage getDamage() {
            return damage;
        }

        /**
         * Sets the value of the damage property.
         * 
         * @param value
         *     allowed object is
         *     {@link Unit.Attack.Damage }
         *     
         */
        public void setDamage(Unit.Attack.Damage value) {
            this.damage = value;
        }

        /**
         * Gets the value of the rate property.
         * 
         */
        public float getRate() {
            return rate;
        }

        /**
         * Sets the value of the rate property.
         * 
         */
        public void setRate(float value) {
            this.rate = value;
        }

        /**
         * Gets the value of the range property.
         * 
         */
        public float getRange() {
            return range;
        }

        /**
         * Sets the value of the range property.
         * 
         */
        public void setRange(float value) {
            this.range = value;
        }

        /**
         * Gets the value of the projectileSpeed property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProjectileSpeed() {
            return projectileSpeed;
        }

        /**
         * Sets the value of the projectileSpeed property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProjectileSpeed(String value) {
            this.projectileSpeed = value;
        }

        /**
         * Gets the value of the attackCapabilitie property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttackCapabilitie() {
            if (attackCapabilitie == null) {
                return "none";
            } else {
                return attackCapabilitie;
            }
        }

        /**
         * Sets the value of the attackCapabilitie property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttackCapabilitie(String value) {
            this.attackCapabilitie = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="max" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="min" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *       &lt;attribute ref="{http://clentfort.github.com/dota2/dota}damageType"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "max",
            "min"
        })
        public static class Damage {

            protected int max;
            protected int min;
            @XmlAttribute(name = "damageType", namespace = "http://clentfort.github.com/dota2/dota")
            protected String damageType;

            /**
             * Gets the value of the max property.
             * 
             */
            public int getMax() {
                return max;
            }

            /**
             * Sets the value of the max property.
             * 
             */
            public void setMax(int value) {
                this.max = value;
            }

            /**
             * Gets the value of the min property.
             * 
             */
            public int getMin() {
                return min;
            }

            /**
             * Sets the value of the min property.
             * 
             */
            public void setMin(int value) {
                this.min = value;
            }

            /**
             * Gets the value of the damageType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDamageType() {
                if (damageType == null) {
                    return "physical";
                } else {
                    return damageType;
                }
            }

            /**
             * Sets the value of the damageType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDamageType(String value) {
                this.damageType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="strength" type="{http://clentfort.github.com/dota2/dota}unitAttribute"/>
     *         &lt;element name="intelligence" type="{http://clentfort.github.com/dota2/dota}unitAttribute"/>
     *         &lt;element name="agility" type="{http://clentfort.github.com/dota2/dota}unitAttribute"/>
     *       &lt;/sequence>
     *       &lt;attribute name="primary" default="strength">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="strength"/>
     *             &lt;enumeration value="intelligence"/>
     *             &lt;enumeration value="agility"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "strength",
        "intelligence",
        "agility"
    })
    public static class Attributes {

        @XmlElement(required = true)
        protected UnitAttribute strength;
        @XmlElement(required = true)
        protected UnitAttribute intelligence;
        @XmlElement(required = true)
        protected UnitAttribute agility;
        @XmlAttribute(name = "primary")
        protected String primary;

        /**
         * Gets the value of the strength property.
         * 
         * @return
         *     possible object is
         *     {@link UnitAttribute }
         *     
         */
        public UnitAttribute getStrength() {
            return strength;
        }

        /**
         * Sets the value of the strength property.
         * 
         * @param value
         *     allowed object is
         *     {@link UnitAttribute }
         *     
         */
        public void setStrength(UnitAttribute value) {
            this.strength = value;
        }

        /**
         * Gets the value of the intelligence property.
         * 
         * @return
         *     possible object is
         *     {@link UnitAttribute }
         *     
         */
        public UnitAttribute getIntelligence() {
            return intelligence;
        }

        /**
         * Sets the value of the intelligence property.
         * 
         * @param value
         *     allowed object is
         *     {@link UnitAttribute }
         *     
         */
        public void setIntelligence(UnitAttribute value) {
            this.intelligence = value;
        }

        /**
         * Gets the value of the agility property.
         * 
         * @return
         *     possible object is
         *     {@link UnitAttribute }
         *     
         */
        public UnitAttribute getAgility() {
            return agility;
        }

        /**
         * Sets the value of the agility property.
         * 
         * @param value
         *     allowed object is
         *     {@link UnitAttribute }
         *     
         */
        public void setAgility(UnitAttribute value) {
            this.agility = value;
        }

        /**
         * Gets the value of the primary property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrimary() {
            if (primary == null) {
                return "strength";
            } else {
                return primary;
            }
        }

        /**
         * Sets the value of the primary property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrimary(String value) {
            this.primary = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="xp" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="gold">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="max" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="min" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "xp",
        "gold"
    })
    public static class Bounty {

        protected int xp;
        @XmlElement(required = true)
        protected Unit.Bounty.Gold gold;

        /**
         * Gets the value of the xp property.
         * 
         */
        public int getXp() {
            return xp;
        }

        /**
         * Sets the value of the xp property.
         * 
         */
        public void setXp(int value) {
            this.xp = value;
        }

        /**
         * Gets the value of the gold property.
         * 
         * @return
         *     possible object is
         *     {@link Unit.Bounty.Gold }
         *     
         */
        public Unit.Bounty.Gold getGold() {
            return gold;
        }

        /**
         * Sets the value of the gold property.
         * 
         * @param value
         *     allowed object is
         *     {@link Unit.Bounty.Gold }
         *     
         */
        public void setGold(Unit.Bounty.Gold value) {
            this.gold = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="max" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="min" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "max",
            "min"
        })
        public static class Gold {

            protected int max;
            protected int min;

            /**
             * Gets the value of the max property.
             * 
             */
            public int getMax() {
                return max;
            }

            /**
             * Sets the value of the max property.
             * 
             */
            public void setMax(int value) {
                this.max = value;
            }

            /**
             * Gets the value of the min property.
             * 
             */
            public int getMin() {
                return min;
            }

            /**
             * Sets the value of the min property.
             * 
             */
            public void setMin(int value) {
                this.min = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="turnRate" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "speed",
        "turnRate"
    })
    public static class Movement {

        protected int speed;
        protected float turnRate;

        /**
         * Gets the value of the speed property.
         * 
         */
        public int getSpeed() {
            return speed;
        }

        /**
         * Sets the value of the speed property.
         * 
         */
        public void setSpeed(int value) {
            this.speed = value;
        }

        /**
         * Gets the value of the turnRate property.
         * 
         */
        public float getTurnRate() {
            return turnRate;
        }

        /**
         * Sets the value of the turnRate property.
         * 
         */
        public void setTurnRate(float value) {
            this.turnRate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="health" type="{http://clentfort.github.com/dota2/dota}unitStatus"/>
     *         &lt;element name="mana" type="{http://clentfort.github.com/dota2/dota}unitStatus"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "health",
        "mana"
    })
    public static class Stats {

        @XmlElement(required = true)
        protected UnitStatus health;
        @XmlElement(required = true)
        protected UnitStatus mana;

        /**
         * Gets the value of the health property.
         * 
         * @return
         *     possible object is
         *     {@link UnitStatus }
         *     
         */
        public UnitStatus getHealth() {
            return health;
        }

        /**
         * Sets the value of the health property.
         * 
         * @param value
         *     allowed object is
         *     {@link UnitStatus }
         *     
         */
        public void setHealth(UnitStatus value) {
            this.health = value;
        }

        /**
         * Gets the value of the mana property.
         * 
         * @return
         *     possible object is
         *     {@link UnitStatus }
         *     
         */
        public UnitStatus getMana() {
            return mana;
        }

        /**
         * Sets the value of the mana property.
         * 
         * @param value
         *     allowed object is
         *     {@link UnitStatus }
         *     
         */
        public void setMana(UnitStatus value) {
            this.mana = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="day" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="night" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "day",
        "night"
    })
    public static class Vision {

        protected int day;
        protected int night;

        /**
         * Gets the value of the day property.
         * 
         */
        public int getDay() {
            return day;
        }

        /**
         * Sets the value of the day property.
         * 
         */
        public void setDay(int value) {
            this.day = value;
        }

        /**
         * Gets the value of the night property.
         * 
         */
        public int getNight() {
            return night;
        }

        /**
         * Sets the value of the night property.
         * 
         */
        public void setNight(int value) {
            this.night = value;
        }

    }

}
